# Generated by Django 4.0.4 on 2023-05-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, verbose_name='用户名')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
            ],
        ),
    ]
