# Generated by Django 4.0.4 on 2023-05-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.CharField(default='you can edit your introduction here', max_length=50, verbose_name='简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='your nickname', max_length=25, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
