# Generated by Django 4.2.1 on 2023-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0002_account_introduction_account_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_content', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pyq',
            fields=[
                ('avatar', models.IntegerField(verbose_name='头像')),
                ('username', models.CharField(max_length=25, verbose_name='用户名')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('posttime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('image_contain', models.ManyToManyField(to='android_server.image')),
            ],
        ),
    ]
