# Generated by Django 4.2.1 on 2023-05-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0003_image_pyq'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('oppo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='对面ID')),
                ('msg_cnt', models.IntegerField(verbose_name='消息数量')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=500, verbose_name='消息内容')),
                ('msg_ID', models.IntegerField(verbose_name='消息序号')),
                ('msg_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chats_contain', models.ManyToManyField(to='android_server.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='msg_contain',
            field=models.ManyToManyField(to='android_server.message'),
        ),
    ]
