# Generated by Django 4.2.1 on 2023-05-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0004_chat_message_chats_chat_msg_contain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chats_contain',
            new_name='chat_contain',
        ),
    ]
