# Generated by Django 4.2.1 on 2023-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0005_rename_chats_contain_chats_chat_contain'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.IntegerField(default=0, verbose_name='头像'),
        ),
    ]
