# Generated by Django 4.1.4 on 2023-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0007_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar', verbose_name='头像'),
        ),
    ]
