# Generated by Django 4.0.4 on 2023-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0007_followperson_remove_chats_chat_contain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('oppo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='对面ID')),
                ('msg_cnt', models.IntegerField(verbose_name='消息数量')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_content', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=500, verbose_name='消息内容')),
                ('msg_ID', models.IntegerField(verbose_name='消息序号')),
                ('msg_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
        ),
        migrations.AlterField(
            model_name='followperson',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='pyq',
            fields=[
                ('avatar', models.IntegerField(verbose_name='头像')),
                ('tag', models.CharField(max_length=25, verbose_name='tag')),
                ('username', models.CharField(max_length=25, verbose_name='用户名')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('posttime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('image_contain', models.ManyToManyField(to='android_server.image')),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('chat_contain', models.ManyToManyField(to='android_server.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='msg_contain',
            field=models.ManyToManyField(to='android_server.message'),
        ),
    ]
