# Generated by Django 4.0.4 on 2023-06-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0008_chat_image_message_alter_followperson_id_pyq_chats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='chat_contain',
        ),
        migrations.DeleteModel(
            name='chat',
        ),
        migrations.DeleteModel(
            name='chats',
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
