# Generated by Django 4.0.4 on 2023-06-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0009_remove_chats_chat_contain_delete_chat_delete_chats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.IntegerField()),
                ('oppo_id', models.IntegerField(verbose_name='对面ID')),
                ('msg_cnt', models.IntegerField(verbose_name='消息数量')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=500, verbose_name='消息内容')),
                ('msg_ID', models.IntegerField(verbose_name='消息序号')),
                ('msg_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('chat_contain', models.ManyToManyField(to='android_server.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='msg_contain',
            field=models.ManyToManyField(to='android_server.message'),
        ),
    ]
