# Generated by Django 4.0.4 on 2023-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0011_chat_msg_contain_alter_chat_msg_contain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg_contain',
            field=models.ManyToManyField(to='android_server.message'),
        ),
        migrations.DeleteModel(
            name='chat_msg_contain',
        ),
    ]
