# Generated by Django 4.0.4 on 2023-06-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0014_remove_message_is_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='chat_contain',
        ),
        migrations.DeleteModel(
            name='chat',
        ),
        migrations.DeleteModel(
            name='chats',
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
