# Generated by Django 4.0.4 on 2023-06-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0008_alter_account_avatar'),
        ('android_server', '0017_message_is_send'),
    ]

    operations = [
    ]
