# Generated by Django 4.0.4 on 2023-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0018_merge_0008_alter_account_avatar_0017_message_is_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_send',
        ),
    ]
