# Generated by Django 4.0.4 on 2023-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0019_remove_message_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_send',
            field=models.BooleanField(default=True),
        ),
    ]
