# Generated by Django 4.0.4 on 2023-06-06 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0020_message_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='地点'),
            preserve_default=False,
        ),
    ]
