# Generated by Django 4.0.4 on 2023-06-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0021_pyq_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyq',
            name='avatar',
        ),
    ]
