# Generated by Django 4.0.4 on 2023-06-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0026_alter_pyq_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='shoucang_account_contain',
            field=models.ManyToManyField(related_name='shoucang', to='android_server.account'),
        ),
    ]
