# Generated by Django 4.0.4 on 2023-06-10 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0027_pyq_shoucang_account_contain'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_userid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
