# Generated by Django 4.0.4 on 2023-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0028_comment_comment_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_userid',
            field=models.IntegerField(default=0),
        ),
    ]
