# Generated by Django 4.0.4 on 2023-06-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0029_alter_comment_comment_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyq',
            name='image_contain',
        ),
        migrations.AddField(
            model_name='image',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_content',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
