# Generated by Django 4.0.4 on 2023-06-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0030_remove_pyq_image_contain_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='image_contain',
            field=models.ManyToManyField(to='android_server.image'),
        ),
    ]
