# Generated by Django 4.0.4 on 2023-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0031_pyq_image_contain'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
