# Generated by Django 4.0.4 on 2023-06-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0036_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='block',
        ),
    ]
