# Generated by Django 4.0.4 on 2023-06-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0037_delete_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('user_ID', models.IntegerField()),
            ],
        ),
    ]
