# Generated by Django 4.0.4 on 2023-06-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_server', '0039_delete_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('user_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
